#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - jq
  - btrfs-progs
  - sed
  - wget
  - git
  - unzip
  - lvm2

runcmd:
  - curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  - unzip -q /tmp/awscliv2.zip -d /tmp && /tmp/aws/install
  - cd /opt && git clone https://github.com/satriobio/amazon-ebs-autoscale.git
  - sh /opt/amazon-ebs-autoscale/install.sh /var/lib/docker 2>&1 > /var/log/ebs-autoscale-install.log
